### ISSUE TITLE
Custom selectors breaking

### ISSUE THREAD

**Issue by iamso** [postcss/postcss-selector-parser#157]
Hi 

while switching my project template from **postcss-cssnext** to **postcss-preset-env** I have discovered that custom selectors are not parsed correctly anymore. 

Simple use cases still work, but if you add multiple custom selectors it starts getting weird.

I have posted [this issue](https://github.com/csstools/postcss-preset-env/issues/89) with **postcss-preset-env** and @jonathantneal suggested that the problem might be with this package.

Here is an example:

```postcss
@custom-selector :--nav-open-header .site-loaded .nav-toggle-input:checked ~ .site-header;
@custom-selector :--nav-open-header-no-touch .site-loaded.no-touchevents .nav-toggle-input:checked ~ .site-header;

:--nav-open-header ul,
:--nav-open-header-no-touch:hover ul {
  background: red;
}
```

The expected output is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded .no-touchevents .nav-toggle-input:checked~.site-header:hover ul {
  background: red;
}
```

But what you get instead is this:
```css
.site-loaded .nav-toggle-input:checked~.site-header ul,
.site-loaded
.no-touchevents 
.nav-toggle-input
:checked
~
.site-header:hover ul {
  background: red;
}
```

I have tested this example here https://preset-env.cssdb.org/playground and it behaves exactly as in my local setup.

As you can see, it breaks the `:checked` part of the selector and therefore it doesn't work.

It does work if you only use one, but with two, like in this example, it breaks the second one.

Thanks
Steve
