### ISSUE TITLE
Error on scss namespace like `font: `

### ISSUE THREAD

**Issue by JounQin** [postcss/postcss-selector-parser#206]
```scss
a {
  font: {
    size: 10px;
    weight: 400;
  }
}
```

Error: Error: Expected a pseudo-class or pseudo-element.

related: https://github.com/kristerkari/stylelint-scss/issues/359
