### ISSUE TITLE
broken attribute selectors with `\a` and ` ` characters

### ISSUE THREAD

**Issue by alexander-akait** [postcss/postcss-selector-parser#246]
Unfortunately this example fails at the moment. It turns into `\a` into `a` (removes only the `\`). It seems a different problem though.

_Originally posted by @ludofischer in https://github.com/postcss/postcss-selector-parser/pull/245#r629639304_

Example:
```css
// http://jsfiddle.net/BoltClock/AHuvh/6
a[href="\a  http://google.com"] {
  color: red;
}
```
