### ISSUE TITLE
walkClasses doesn't work as expected - it walk through the animation percents also

### ISSUE THREAD

**Issue by studentIvan** [postcss/postcss-selector-parser#247]
I use `root.walkClasses((classNode) => {` inside the processor function but it walks thought the percents of this animation example:

```css
@keyframes animation-11sr958 {

  0%,
  100%,
  13.33%,
  80% {
    transform: translate(0, 0)
  }

  20% {
    transform: translate(0, -8px)
  }

  26.67%,
  33.33% {
    transform: translate(0, -10px)
  }

  40% {
    transform: translate(0, -6px)
  }

  46.67% {
    transform: translate(0, -2px)
  }

  53.33% {
    transform: translate(0, 3px)
  }

  60% {
    transform: translate(0, 2px)
  }

  66.67% {
    transform: translate(0, -1px)
  }
}
```

E.g. 67% is a "class" here...

I had to use my own check inside:

```js
const charCodeZero = '0'.charCodeAt(0);
const charCodeNine = '9'.charCodeAt(0);

// ...
const n = v.charCodeAt(0);
if (!(n >= charCodeZero && n <= charCodeNine)) {
  // real classname, not percentage
}
```
