### ISSUE TITLE
Cannot use with postcss-apply

### ISSUE THREAD

**Issue by morishitter** [postcss/postcss-selector-parser#28]
I start to use [postcss-apply](https://github.com/pascalduez/postcss-apply) with cssnext (postcss-selector-parser is used in cssnext), but the following error is occured.

```
Error: Expected pseudo-class or pseudo-element
```

and here is my CSS code.

```css
:root {
  --truncate: {
    white-space: nowrap;
    overflow: hidden;
    text-overflow: ellipsis;
  }
}
```

I wish your help. Thanks.
